/**
*   @file    Can_43_LLCE_VS_0_PBcfg.h
*   @version 1.0.11
*
*   @brief   AUTOSAR Can_43_LLCE - module interface
*   @details Configuration settings generated by user settings.
*
*   @addtogroup CAN_LLCE
*   @{
*   Project              : RTD AUTOSAR 4.4
*   Platform             : CORTEXM
*   Peripheral           : LLCE
*   Dependencies         : 
*
*   Autosar Version      : 4.4.0
*   Autosar Revision     : ASR_REL_4_4_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 1.0.11
*   Build Version        : S32_RTD_1_0_11_D2511_ASR_REL_4_4_REV_0000_20251121
*
*   Copyright 2020-2025 NXP
*
*   NXP Confidential. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/

#ifndef CAN_43_LLCE_VS_0_PBCFG_H
#define CAN_43_LLCE_VS_0_PBCFG_H

#ifdef __cplusplus
extern "C"{
#endif


/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
/*
* @file           Can_43_LLCE_VS_0_PBcfg.h
*/
#define CAN_43_LLCE_VENDOR_ID_VS_0_PBCFG_H                  43
#define CAN_43_LLCE_AR_RELEASE_MAJOR_VERSION_VS_0_PBCFG_H           4
#define CAN_43_LLCE_AR_RELEASE_MINOR_VERSION_VS_0_PBCFG_H           4
#define CAN_43_LLCE_AR_RELEASE_REVISION_VERSION_VS_0_PBCFG_H        0
#define CAN_43_LLCE_SW_MAJOR_VERSION_VS_0_PBCFG_H           1
#define CAN_43_LLCE_SW_MINOR_VERSION_VS_0_PBCFG_H           0
#define CAN_43_LLCE_SW_PATCH_VERSION_VS_0_PBCFG_H           11

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/

/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/
#define CAN_43_LLCE_CONFIG_VS_0_PB\
    extern const Can_43_LLCE_ConfigType Can_43_LLCE_Config_VS_0;

#ifdef __cplusplus
}
#endif

#endif /* _CAN_43_LLCE_VS_0_PBCFG_H_ */

/** @} */

